### ISSUE TITLE
juvix.org installer snippet is invalid

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix-docs#59]
https://juvix.org displays the curl snippet to run the https://github.com/anoma/juvix-installer

When you hover over the snippet an message appears "click to copy". This copies the snippet into the clipboard.

However the snippet cannot be pasted into a shell directly because it contains newlines, which make it invalid:

<img width="997" alt="Screenshot 2023-06-16 at 16 43 20" src="https://github.com/anoma/juvix-docs/assets/92877/cbd11bd7-e478-4bd4-a67a-cbbc2c522466">

If you paste this into a zsh shell you get an error:

```
zsh: parse error near `|'
```

The snippet should be copied as a single line.

**Comment by pedrorezende** [comment]
Thank you for pointing that out. It's been fixed here: https://github.com/heliaxdev/juvix-website/commit/7caf4f6587ddcc96dbeb3bf061fa2861b4095c2b .

**Comment by paulcadman** [comment]
Thanks for looking into this @pedrorezende , however it still doesn't work because the get.juvix.org link is now a redirect.

Please can you change it to:

```
curl --proto '=https' --tlsv1.2 -sSfL https://get.juvix.org | sh
```

(Adding the `-L` flag directs `curl` to follow the redirect, and the snippet works as intended).

**Comment by paulcadman** [comment]
This has now been fixed
